base:
    is_dev : true
    serial_number : 1.0.0
    service_name : example
    service_displayname : exampleserver
    sercice_desc : example微服务
mysql_info:
    host : localhost
    port : 3306
    username : root
    password : 123456
    database : oauth_db
redis_info:
    addrs: ["127.0.0.1:6379"]
    password: 123456
    group_name: oauth2
    db: 0
etcd_info:
    addrs: ["127.0.0.1:2379"]
    timeout: 3
consul_addr: http://192.155.1.150:8500
consul_tag: dev
port: 82
